# Generated by Django 5.0.7 on 2024-08-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
