# Generated by Django 5.0.7 on 2024-08-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Service',
        ),
    ]
